# Generated by Django 5.0.7 on 2024-07-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
